apiVersion: beam.stellar.dev/v1alpha1
kind: BeamWebApp
metadata:
  labels:
    app.kubernetes.io/name: stellar-operator
    app.kubernetes.io/managed-by: kustomize
  name: beamwebapp-sample
spec:
  # TODO(user): Add fields here
